### ISSUE TITLE
The CONTRIBUTING.md needed to be updated.

### ISSUE THREAD

**Issue by abhisekmazumdar** [devcpune/kaleidoscope#17]
I'm not very familiar with what are the things needed while sharing a Facebook Spark AR Project. If anyone who has worked with this. Kindly share your thought, even better raise a PR updating the CONTRIBUTING.md.

**Comment by Arsenic-ATG** [comment]
hi @abhisekmazumdar I am willing to work on this issue, here are the things I think should a sparkAR project have :- 
1. Project itself
2. Trial link
3. Preferably some screenshots/gifs showcasing their AR filter.

if you allow, I may start my work of updating CONTRIBUTING.md.

**Comment by abhisekmazumdar** [comment]
Yes sure. Raise a PR our team will review it.
