### ISSUE TITLE
Add advantages of contributing

### ISSUE THREAD

**Issue by shriaas2898** [devcpune/kaleidoscope#2]
The _advantages of contributing_ section is currently empty, add key advantages.

**Comment by Arsenic-ATG** [comment]
hello @shriaas2898 ,if you allow then I am willing to work on this issue.
but I have a doubt : 
Q. Does the advantages should be this repository specific or contributing to open source in general ?

**Comment by abhisekmazumdar** [comment]
Hi as we are restructuring this repo as a platform to showcase the work on **Facebook Spark AR** by the community. So the advantage should be around this context.

**Comment by Arsenic-ATG** [comment]
@abhisekmazumdar ok , and thank you for replying 🙂

so should I start the working on it ?

**Comment by abhisekmazumdar** [comment]
Yes sure @Arsenic-ATG

**Comment by Arsenic-ATG** [comment]
@abhisekmazumdar [pull request issued](https://github.com/devcpune/kaleidoscope/pull/18)

Right now I have only added 2 points, If there are any other points which you think I have missed then do let me know I will make the changes accordingly.

**Comment by abhisekmazumdar** [comment]
Thanks, @Arsenic-ATG for the PR. Closig this issue.
