### ISSUE TITLE
Add a CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Amorpheuz** [devcpune/kaleidoscope#4]
Having a specific `CODE_OF_CONDUCT.md` file will allow GitHub to mention it at various places, ensuring people have more chances to be familiar with it.

Example of how GitHub takes benefit of the file:
![image](https://user-images.githubusercontent.com/22113778/88679318-f21cae00-d10c-11ea-9940-9fa13a18d1d1.png)

Since, according to [CONTRIBUTING.md](https://github.com/devcpune/kaleidoscope/blob/master/docs/CONTRIBUTING.md), we are following Facebook's Code of Conduct, the same line repeated in the `CODE_OF_CONDUCT.md` file should be enough. 

```markdown
## Code of Conduct

Please refer to the **[Code of Conduct](https://engineering.fb.com/codeofconduct/)** adopted by Facebook to understand what kind of behaviour will and not be tolerated when contributing to this project
```

This can either be a `Community default` file as indicated by [steps here](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file), OR a repo specific file by adding it to `docs/CODE_OF_CONDUCT.md` alongside the `CONTRIBUTING.md` file.

**Comment by vj-codes** [comment]
@Amorpheuz May I work on this?

**Comment by sayak-sarkar** [comment]
@vj-codes Sure! Simply assign the issue to yourself and send in a PR! :)

**Comment by AJV009** [comment]
@Amorpheuz the issue has been fixed by @vj-codes
