### ISSUE TITLE
Enable Content Reports for Repository Contributors

### ISSUE THREAD

**Issue by Amorpheuz** [devcpune/kaleidoscope#5]
[Content Reports](https://docs.github.com/en/github/building-a-strong-community/managing-reported-content-in-your-organizations-repository) allow contributors to the repo to report abuse in the repository to the maintainers. Enabling them by following the [outlined steps](https://docs.github.com/en/github/building-a-strong-community/managing-how-contributors-report-abuse-in-your-organizations-repository) will allow DevC Pune to maintain a safer environment similar to the Facebook group.

More information related to this can be found [here](https://docs.github.com/en/github/building-a-strong-community/moderating-comments-and-conversations). These steps should be performed by the repository Admin.

**Comment by abhisekmazumdar** [comment]
Thank You @Amorpheuz I have enabled Content Reports for this repo.
