### ISSUE TITLE
Add "projects" folder

### ISSUE THREAD

**Issue by AJV009** [devcpune/kaleidoscope#9]
If the repo code section starts having projects more than what the screen can hold in the view point then the readme would get hidden!
So maybe having a folder named "project" and adding/moving all the projects/contributions to that folder would help!

**Comment by gmanasi13** [comment]
Hi, I can take this up and update the README as well as contributing.md file to reflect the changes.
@AJV009  Please assign the issue to me.

**Comment by gmanasi13** [comment]
@AJV009 Created a pull request with the required changes. Please verify.

**Comment by AJV009** [comment]
Hey @gmanasi13  I just added one more reviewer as the projects folder is still under planning.
